version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build:
    executor:
      name: android/android_docker
      tag: 2025.03.1
      resource_class: large 
    steps:
      - checkout
      - android/restore_gradle_cache
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - android/save_gradle_cache
      - store_artifacts:
          path: app/build/outputs/apk/release/
      
  test:
    executor:
      name: android/android_docker
      tag: 2025.03.1
    steps:
      - checkout
      - android/restore_gradle_cache
      - android/run_tests:
          test_command: ./gradlew testDebug
      - android/save_gradle_cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results

workflows:
  build-only:
    jobs:
      - build-arm64
