version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build-signed:
    executor:
      name: android/android_docker
      tag: 2025.03.1
      resource_class: large
    steps:
      - checkout
      
      - run:
          name: Decode Keystore
          command: echo $BASE64_KEYSTORE | base64 --decode > app/keystore.jks
      
      - android/restore_gradle_cache
      
      - run:
          name: Build Signed Release APK
          command: ./gradlew assembleRelease -x test
          environment:            
            GRADLE_OPTS: "-Xmx3g -Dorg.gradle.daemon=false"
            _JAVA_OPTIONS: "-Xmx4g"
            LASTFM_API_KEY: $LASTFM_API_KEY
            LASTFM_SECRET: $LASTFM_SECRET
      
      - android/save_gradle_cache
      
      - store_artifacts:
          path: app/build/outputs/apk/arm64/release/
          destination: signed-apk
      
      - store_artifacts:
          path: app/build/outputs/bundle/arm64/release/
          destination: signed-aab

workflows:
  build-and-sign:
    jobs:
      - build-signed
